export const COMMANDS_PUSH_TO_END = "COMMANDS_PUSH_TO_END";
export const COMMANDS_DELETE_BY_ID = "COMMANDS_DELETE_BY_ID";
export const COMMANDS_EMPTY_ARRAY = "COMMANDS_EMPTY_ARRAY";
export const COMMANDS_CREATE_ADD_POOL = "COMMANDS_CREATE_ADD_POOL";
export const COMMANDS_CREATE_SET_TEXT = "COMMANDS_CREATE_SET_TEXT";
export const COMMANDS_CREATE_SET_TYPES = "COMMANDS_CREATE_SET_TYPES";